/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;
import proyectofinal.CommandCenter;

/**
 *
 * @author vjalvare
 */
public class SeleccionPelicula extends javax.swing.JFrame {

    
    CommandCenter cm= CommandCenter.getUniqueInstance();
//    static ColaPelicula peliCol = new ColaPelicula();
//    static ColaPelicula peliPrecio = new ColaPelicula();
    Butaca but = new Butaca();
    Butaca2 but2 = new Butaca2();
    String [] strings = new String[99];
    int id;
    /**
     * Creates new form UI
     */
    public SeleccionPelicula() {
        initComponents();
        //peliCol.encolar(new NodoColaPelicula(new Pelicula(1, "Star Wars", 2500, 1)));
        //peliCol.encolar(new NodoColaPelicula(new Pelicula(2, "Pokemon", 3000, 2)));
        //peliPrecio.encolar(new NodoColaPelicula(new Pelicula(1, "Star Wars", 2500, 1)));
        //peliPrecio.encolar(new NodoColaPelicula(new Pelicula(2, "Pokemon", 3000, 2)));
        cm.rellenarPeli();
        rellenarPane();
        System.out.println();
        //rellenarPane(cm.peliCol.atender());
    }
    String peli="";
    /*static int ident;
    static int cant;
    static int costo;
    static String tnt;
    
    
    public static int getIdent() {
        return costo;
    }

    public static void setIdent(int ident) {
        SeleccionPelicula.ident = ident;
    }
    
    public static int getCosto() {
        return costo;
    }

    public static void setCosto(int costo) {
        SeleccionPelicula.costo = costo;
    }
    
    public static String getTnt() {
        return tnt;
    }

    public static void setTnt(String tnt) {
        SeleccionPelicula.tnt = tnt;
    }
    */
    
    private void rellenarPane(){
        peli+=cm.getPeliCol().toString();
        jTextArea2.setText(peli);
    }
   /*private void rellenarPane(NodoColaPelicula n){
        if(n != null){
            peli+=n.getDato().toString()+"\n";
            jTextArea2.setText(peli);
           rellenarPane(cm.peliCol.atender());
        }
        
    }*/
    
  /* private void rellenarPane(NodoColaPelicula n){
        if(n != null){
            peliCombo.addItem(n.getDato().toString());
            rellenarPane(peliCol.atender());
        }
        
    }*/
   
   /*if(n!=null){
            strings[i] = n.getDato().toString()+"\n";
            i++;
            rellenarPane(peliCol.atender());
        }
        peliPane.add(strings[i],null);*/

    /*
    if(n != null){
            peliCombo.addItem(n.getDato().toString());
            rellenarCombo(peliCol.atender());
        }
   
   ColaPelicula peliCola = new ColaPelicula();
   String [] strings = new String[99];
   int i=0;
   public void rellenarArreglo(NodoColaPelicula n){
        if(n!=null){
            strings[i] = n.toString();
            i++;
            rellenarArreglo(peliCola.atender());
        }
    }
    */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Por favor, seleccione una pelicula");

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });

        jButton3.setText("Continuar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite la Cantidad");

        jLabel3.setText("Digite ID");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        
    }//GEN-LAST:event_qtyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cm.setIdPeli(Integer.parseInt(ID.getText()));
        cm.setCantTix(Integer.parseInt(qty.getText()));
        switch (cm.getIdPeli()) {
            case 1:
                but.showSeats(cm.getSeats());
                but.setVisible(true);
                cm.setGastoCliente(cm.getCantTix()*(cm.getPeliCol().encuentraPrecio(Integer.parseInt(ID.getText()))));
                //this.setTnt(cm.getPeliCol().extraeX(ident)+" Cantidad "+cant);
                cm.setPeli(cm.getPeliCol().extraeX(Integer.parseInt(ID.getText())).getDato().toString()+" Cantidad "+cm.getCantTix());
                cm.setPelix(cm.getPeliCol().extraeX(Integer.parseInt(ID.getText())).getDato());
                System.out.println(cm.getPeliCol().extraeX(Integer.parseInt(ID.getText()))+" Cantidad "+cm.getCantTix());
                System.out.println(cm.getNombre()+cm.getGastoCliente()+cm.getIdPeli());
                break;
            case 2:
                but2.showSeats2(cm.getSeats2());
                but2.setCont(cm.getCantTix());
                but2.setVisible(true);
                cm.setGastoCliente(cm.getCantTix()*(cm.getPeliCol().encuentraPrecio(cm.getIdPeli())));
                //this.setTnt(cm.getPeliCol().extraeX(ident)+" Cantidad "+cant);
                cm.setPeli(cm.getPeliCol().extraeX(Integer.parseInt(ID.getText())).getDato().toString()+" Cantidad "+cm.getCantTix());
                cm.setPelix(cm.getPeliCol().extraeX(Integer.parseInt(ID.getText())).getDato());
                System.out.println(cm.getPeliCol().extraeX(Integer.parseInt(ID.getText()))+" Cantidad "+cm.getCantTix());
                System.out.println(cm.getNombre()+cm.getGastoCliente()+cm.getIdPeli());
                break;
            default:
                JOptionPane.showMessageDialog(null, "Ingresar ID correcto");
                break;
        }
        ID.setText("");
        qty.setText("");
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        
    }//GEN-LAST:event_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField qty;
    // End of variables declaration//GEN-END:variables
}
